# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msanee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
